apiVersion: apps/v1
kind: Deployment
metadata:
  name: prophet-predictor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prophet-predictor
  template:
    metadata:
      labels:
        app: prophet-predictor
    spec:
      containers:
      - name: prophet-predictor
        image: rahulkaswa/prophet-predictor:v1
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: prophet-predictor
spec:
  selector:
    app: prophet-predictor
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
