## Configuration file for the predictive scaling service

# Prometheus configuration
prometheus:
  url: "http://prometheus:9090"
  timeout: 30
  retry_attempts: 3
  retry_delay: 5

# Metrics to predict
metrics:
  - name: "http_requests"
    query: "rate(http_requests_total[1m])"
    step: "60s"
    range_minutes: 60
    prediction_periods: 5
    prediction_frequency: "min"
    threshold_min: 0.0
    threshold_max: 1000.0
  
  - name: "cpu_usage"
    query: "rate(container_cpu_usage_seconds_total[1m]) * 100"
    step: "60s"
    range_minutes: 120
    prediction_periods: 10
    prediction_frequency: "min"
    threshold_min: 0.0
    threshold_max: 100.0
  
  - name: "memory_usage"
    query: "container_memory_usage_bytes / container_spec_memory_limit_bytes * 100"
    step: "60s"
    range_minutes: 90
    prediction_periods: 8
    prediction_frequency: "min"
    threshold_min: 0.0
    threshold_max: 100.0

# Prophet model configuration
model:
  seasonality_mode: "additive"
  changepoint_prior_scale: 0.05
  seasonality_prior_scale: 10.0
  holidays_prior_scale: 10.0
  daily_seasonality: true
  weekly_seasonality: true
  yearly_seasonality: false
  interval_width: 0.8

# Cache configuration
cache:
  enabled: true
  redis_host: "redis"
  redis_port: 6379
  redis_db: 0
  ttl_seconds: 300
  model_cache_ttl: 3600

# Application settings
debug: false
log_level: "INFO"
data_quality_min_points: 10
model_retrain_interval: 1800  # 30 minutes
