name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  ACR_REGISTRY: hackathon25.azurecr.io
  APP_IMAGE_NAME: hackathonapp
  PROPHET_IMAGE_NAME: prophet-predictor

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      app-changed: ${{ steps.changes.outputs.app }}
      prophet-changed: ${{ steps.changes.outputs.prophet }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Detect file changes
      uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          app:
            - 'app/**'
          prophet:
            - 'prophet-predictor/**'

  build-and-push:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.app-changed == 'true' || needs.detect-changes.outputs.prophet-changed == 'true'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Azure Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.ACR_REGISTRY }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
        
    - name: Extract metadata for app image
      id: meta-app
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.ACR_REGISTRY }}/${{ env.APP_IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}
          
    - name: Extract metadata for prophet image
      id: meta-prophet
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.ACR_REGISTRY }}/${{ env.PROPHET_IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}
          
    - name: Build and push app image
      if: needs.detect-changes.outputs.app-changed == 'true'
      uses: docker/build-push-action@v5
      with:
        context: ./app
        file: ./app/Dockerfile
        push: true
        tags: ${{ steps.meta-app.outputs.tags }}
        labels: ${{ steps.meta-app.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Build and push prophet-predictor image
      if: needs.detect-changes.outputs.prophet-changed == 'true'
      uses: docker/build-push-action@v5
      with:
        context: ./prophet-predictor
        file: ./prophet-predictor/Dockerfile
        push: true
        tags: ${{ steps.meta-prophet.outputs.tags }}
        labels: ${{ steps.meta-prophet.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Log build summary
      run: |
        echo "## Build Summary" >> $GITHUB_STEP_SUMMARY
        echo "| Component | Status | Reason |" >> $GITHUB_STEP_SUMMARY
        echo "|-----------|--------|--------|" >> $GITHUB_STEP_SUMMARY
        if [ "${{ needs.detect-changes.outputs.app-changed }}" == "true" ]; then
          echo "| App | ✅ Built | Changes detected in app/ directory |" >> $GITHUB_STEP_SUMMARY
        else
          echo "| App | ⏭️ Skipped | No changes in app/ directory |" >> $GITHUB_STEP_SUMMARY
        fi
        if [ "${{ needs.detect-changes.outputs.prophet-changed }}" == "true" ]; then
          echo "| Prophet | ✅ Built | Changes detected in prophet-predictor/ directory |" >> $GITHUB_STEP_SUMMARY
        else
          echo "| Prophet | ⏭️ Skipped | No changes in prophet-predictor/ directory |" >> $GITHUB_STEP_SUMMARY
        fi